services:
  coding-agent:
    build: .
    environment:
      - PROBLEM=${PROBLEM:-Calculate the first 10 Fibonacci numbers}
      - MODEL_PROVIDER=docker-model-runner
      # FIXED: Use correct Docker Model Runner endpoint with port 12434
      - OPENAI_BASE_URL=http://host.docker.internal:12434/v1
      - OPENAI_API_KEY=irrelevant
      - MODEL_NAME=llama.cpp
      - MCPGATEWAY_URL=http://mcp-gateway:8811
    volumes:
      - ./output:/app/output
      - ./sandbox-output:/app/sandbox-output
    depends_on:
      - mcp-gateway

  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - "8811:8811"
    use_api_socket: true
    command:
      - --transport=sse
      - --servers=node-code-sandbox
      - --tools=run_js

# Docker Model Runner models configuration
models:
  qwen3-small:
    model: ai/qwen3:8B-Q4_0 # 4.44 GB
    context_size: 15000 # 7 GB VRAM
  qwen3-medium:
    model: ai/qwen3:14B-Q6_K # 11.28 GB
    context_size: 15000 # 15 GB VRAM
