services:
  coding-agent:
    build: .
    environment:
      - PROBLEM=${PROBLEM:-Calculate the first 10 Fibonacci numbers}
      - MODEL_PROVIDER=docker-model-runner
      - MCPGATEWAY_URL=http://mcp-gateway:8811
    volumes:
      - ./output:/app/output
      - ./sandbox-output:/app/sandbox-output
    depends_on:
      - mcp-gateway
    # NEW: Service-level model configuration following Agentic Compose pattern
    models:
      qwen3:
        endpoint_var: OPENAI_BASE_URL
        model_var: OPENAI_MODEL

  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - "8811:8811"
    use_api_socket: true
    command:
      - --transport=sse
      - --servers=node-code-sandbox
      - --tools=run_js

# NEW: Top-level models section following Agentic Compose pattern
models:
  qwen3:
    model: ai/qwen3:8B-Q4_0
    context_size: 8096
