services:
  agents-ui:
    build:
      context: agent-ui
    ports:
      - "3000:3000"
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
    depends_on:
      - mcp-gateway

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    # use docker API socket to start MCP servers
    use_api_socket: true
    command:
      - --transport=sse
      # securely embed secrets into the gateway
      - --secrets=/run/secrets/mcp_secret
      # add any MCP servers you want to use
      - --servers=github,duckduckgo,fetch
    secrets:
      - mcp_secret

models:
  recommendation_model:
    # pre-pull the model when starting Docker Model Runner
    model: ai/qwen3:8B-Q4_0 # 4.44 GB
    context_size: 15000 # 7 GB VRAM

# mount the secrets file for MCP servers
secrets:
  mcp_secret:
    file: ./.mcp.env
