services:
  coding-agent:
    build: .
    environment:
      - PROBLEM=${PROBLEM:-Calculate the first 10 Fibonacci numbers}
      - MODEL_PROVIDER=docker-model-runner
      - MODEL_RUNNER_URL=http://localhost:8000
      - MODEL_RUNNER_MODEL=qwen3-small
    volumes:
      - ./output:/app/output
      - ./sandbox-output:/app/sandbox-output
      - /var/run/docker.sock:/var/run/docker.sock
    models:
      qwen3-small:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

models:
  qwen3-small:
    model: ai/qwen3:8B-Q4_0 # 4.44 GB
    context_size: 15000 # 7 GB VRAM
  qwen3-medium:
    model: ai/qwen3:14B-Q6_K # 11.28 GB
    context_size: 15000 # 15 GB VRAM

# Usage:
# Default (Docker Model Runner): docker compose up --build
# With OpenAI: docker compose -f compose.yaml -f compose.openai.yaml up --build
# With Docker Offload: docker compose -f compose.yaml -f compose.offload.yaml up --build
