services:
  # AI coding agent using MCP for Node.js code execution  
  coding-agent:
    build: .
    environment:
      - PROBLEM=${PROBLEM:-Calculate the first 10 Fibonacci numbers}
    volumes:
      - ./output:/app/output
      - ./sandbox-output:/app/sandbox-output
    depends_on:
      - mcp-gateway

  # MCP Gateway for coordinating MCP servers
  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - "3001:3001"
    environment:
      - MCP_SERVERS=node-sandbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Default uses Docker Model Runner (local models)
# Usage:
# Default (DMR): docker compose up --build
# With OpenAI: docker compose -f compose.yaml -f compose.openai.yaml up --build  
# With Offload: docker compose -f compose.yaml -f compose.offload.yaml up --build
