services:
  coding-agent:
    build: .
    environment:
      - PROBLEM=${PROBLEM:-Calculate the first 10 Fibonacci numbers}
      - MODEL_PROVIDER=${MODEL_PROVIDER:-local}
      - MODEL_NAME=${MODEL_NAME:-llama3.2:3b}
    volumes:
      - ./output:/app/output
      - ./sandbox-output:/app/sandbox-output
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - model

  model:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0

volumes:
  ollama_data:

# Usage:
# Default (local models): docker compose up --build
# With custom problem: PROBLEM="Your coding problem" docker compose up --build
